//Map 1
export 'npc_controller_map1/charity_controller.dart';
export 'npc_controller_map1/nat_controller.dart';
export 'npc_controller_map1/pisujohn_controller.dart';
//Map 2
export 'npc_controller_map2/jammy_controller.dart';
export 'npc_controller_map2/ellen_controller.dart';
export 'npc_controller_map2/passwordz_controller.dart';
//Map 3
export 'npc_controller_map3/topsu_controller.dart';
export 'npc_controller_map3/nor_controller.dart';
export 'npc_controller_map3/sholzi_controller.dart';
//Map 4
export 'npc_controller_map4/kitty_controller.dart';
export 'npc_controller_map4/fox_controller.dart';
export 'npc_controller_map4/fishy_controller.dart';

//Map 5
export 'npc_controller_map5/leman_controller.dart';
export 'npc_controller_map5/pay_controller.dart';
